apiVersion: v1
kind: Service
metadata:
  name: CUSTOMCONNECTORNAME
  annotations:
    connectors.aiops.ibm.com/cert-create-enabled: "true"
  labels:
    app: CUSTOMCONNECTORNAME
    instance: connector
spec:
  selector:
    app: CUSTOMCONNECTORNAME
    instance: connector
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 9443
